set -e

function main {
  this_script="$1"

  OUTPUT_FILE=aepl-duino-tinkercad-generated.ino

  echo "
// This file has been generated by $this_script
// DO NOT EDIT.

#define TINKERCAD
" > $OUTPUT_FILE

  cat ../aepl-duino.ino >> $OUTPUT_FILE
}

main $0
